apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/metallb/deployment
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
