apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-crs
  namespace: flux-system
spec:
  dependsOn:
    - name: metallb
  interval: 10m
  path: ./infrastructure/metallb/crs
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
