---
apiVersion: fluxcd.controlplane.io/v1
kind: FluxInstance
metadata:
  name: flux
  namespace: flux-system
spec:
  distribution:
    version: "2.x"
    registry: "ghcr.io/fluxcd"
    artifact: "oci://ghcr.io/controlplaneio-fluxcd/flux-operator-manifests"
  components:
    - source-controller
    - source-watcher
    - kustomize-controller
    - helm-controller
    - notification-controller
    - image-reflector-controller
    - image-automation-controller
  cluster:
    type: kubernetes
    size: small
    multitenant: false
    networkPolicy: true
  sync:
    kind: GitRepository
    url: "https://github.com/karlsonley/homelab"
    ref: "refs/heads/main"
    path: "clusters/homelab"
    pullSecret: "flux-system"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: flux-operator
  namespace: flux-system
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Flux Operator"
    gethomepage.dev/description: "GitOps Operator UI"
    gethomepage.dev/group: "Infrastructure"
    gethomepage.dev/icon: "flux-cd.png"
    gethomepage.dev/href: "https://flux.sonley.dev"
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`flux.sonley.dev`)
      kind: Rule
      services:
        - kind: Service
          name: flux-operator
          namespace: flux-system
          port: 8080
      middlewares:
        - name: oidc-auth
          namespace: traefik
