---
apiVersion: fluxcd.controlplane.io/v1
kind: ResourceSet
metadata:
  name: infrastructure
  namespace: flux-system
  annotations:
    fluxcd.controlplane.io/reconcile: "enabled"
    fluxcd.controlplane.io/reconcileEvery: "1h"
    fluxcd.controlplane.io/reconcileTimeout: "5m"
spec:
  inputs:
    - layer: one
      dependsOnLayer: ""
    - layer: two
      dependsOnLayer: one
    - layer: three
      dependsOnLayer: two
    - layer: four
      dependsOnLayer: three
    - layer: five
      dependsOnLayer: four
  resourcesTemplate: |
    ---
    apiVersion: kustomize.toolkit.fluxcd.io/v1
    kind: Kustomization
    metadata:
      name: infrastructure-<< inputs.layer >>
      namespace: flux-system
    spec:
      <<- if ne inputs.dependsOnLayer "" >>
      dependsOn:
        - name: infrastructure-<< inputs.dependsOnLayer >>
      <<- end >>
      interval: 1h
      retryInterval: 1m
      timeout: 5m
      sourceRef:
        kind: GitRepository
        name: flux-system
      path: ./infrastructure/homelab/<< inputs.layer >>
      prune: true
      wait: true
