---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    pod-security.kubernetes.io/enforce: privileged
  name: longhorn
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: longhorn
  namespace: flux-system
spec:
  interval: 30m
  url: https://charts.longhorn.io
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: flux-system
spec:
  releaseName: longhorn
  targetNamespace: longhorn
  interval: 30m
  chart:
    spec:
      chart: longhorn
      version: ">=1.0.0 <2.0.0"
      sourceRef:
        kind: HelmRepository
        name: longhorn
      interval: 5m
  values:
    metrics:
      serviceMonitor:
        enabled: true
        additionalLabels:
          release: kube-prometheus-stack
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn
  namespace: longhorn
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Longhorn"
    gethomepage.dev/description: "Storage"
    gethomepage.dev/group: "Infrastructure"
    gethomepage.dev/icon: "longhorn.png"
    gethomepage.dev/href: "https://longhorn.sonley.dev"
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`longhorn.sonley.dev`)
    services:
    - kind: Service
      name: longhorn-frontend
      namespace: longhorn
      port: 80
    middlewares:
      - name: oidc-auth
        namespace: traefik
