---
apiVersion: v1
kind: Namespace
metadata:
  name: tailscale
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-operator-oauth
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: scaleway-secret-manager
    kind: ClusterSecretStore
  target:
    name: tailscale-operator-oauth
    template:
      type: Opaque
      data:
        client_id: "{{ .client_id }}"
        client_secret: "{{ .client_secret }}"
  data:
  - secretKey: client_id
    remoteRef:
      key: name:tailscale-operator
      property: client_id
      version: latest_enabled
  - secretKey: client_secret
    remoteRef:
      key: name:tailscale-operator
      property: client_secret
      version: latest_enabled
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: tailscale
  namespace: flux-system
spec:
  interval: 30m
  url: https://pkgs.tailscale.com/helmcharts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: flux-system
spec:
  releaseName: tailscale-operator
  targetNamespace: tailscale
  interval: 30m
  chart:
    spec:
      chart: tailscale-operator
      version: ">=1.0.0 <2.0.0"
      sourceRef:
        kind: HelmRepository
        name: tailscale
      interval: 5m
  values:
    operatorConfig:
      defaultTags:
        - tag:k8s
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
  valuesFrom:
  - kind: Secret
    name: tailscale-operator-oauth
    valuesKey: client_id
    targetPath: oauth.clientId
  - kind: Secret
    name: tailscale-operator-oauth
    valuesKey: client_secret
    targetPath: oauth.clientSecret
