---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: scaleway-secret-manager
spec:
  provider:
    scaleway:
      region: nl-ams
      projectId: e6a97697-3b40-482d-99d6-0e6a46f4cd14
      accessKey:
        secretRef:
          name: scw-secrets-manager
          key: access-key-id
          namespace: external-secrets
      secretKey:
        secretRef:
          name: scw-secrets-manager
          key: secret-key
          namespace: external-secrets

---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: external-secrets
  updatePolicy:
    updateMode: "Off"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: external-secrets-cert-controller
  namespace: external-secrets
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: external-secrets-cert-controller
  updatePolicy:
    updateMode: "Off"
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: external-secrets-webhook
  namespace: external-secrets
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: external-secrets-webhook
  updatePolicy:
    updateMode: "Off"
