---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana
  namespace: flux-system
spec:
  interval: 30m
  url: https://grafana.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: flux-system
spec:
  releaseName: loki
  targetNamespace: monitoring
  interval: 30m
  chart:
    spec:
      chart: loki
      version: ">=6.0.0 <7.0.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
      interval: 5m
  values:
    deploymentMode: SingleBinary
    loki:
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      storage:
        type: filesystem
        retention_period: 7d
      limits_config:
        retention_period: 7d
      compactor:
        retention_enabled: true
      schemaConfig:
        configs:
          - from: "2024-04-01"
            store: tsdb
            object_store: filesystem
            schema: v13
            index:
              prefix: loki_index_
              period: 24h
    singleBinary:
      replicas: 1
      persistence:
        enabled: true
        storageClass: longhorn
        size: 10Gi
    backend:
      replicas: 0
    read:
      replicas: 0
    write:
      replicas: 0
    gateway:
      enabled: false
    test:
      enabled: false
    lokiCanary:
      extraArgs:
        - -interval=60s
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: alloy
  namespace: flux-system
spec:
  releaseName: alloy
  targetNamespace: monitoring
  interval: 30m
  chart:
    spec:
      chart: alloy
      version: ">=0.0.0 <1.0.0"
      sourceRef:
        kind: HelmRepository
        name: grafana
      interval: 5m
  values:
    alloy:
      configMap:
        content: |-
          discovery.kubernetes "pods" {
            role = "pod"
          }

          discovery.kubernetes "nodes" {
            role = "node"
          }

          loki.source.kubernetes "pods" {
            targets    = discovery.kubernetes.pods.targets
            forward_to = [loki.write.default.receiver]
          }

          loki.write "default" {
            endpoint {
              url = "http://loki:3100/loki/api/v1/push"
            }
          }
    controller:
      type: daemonset
