---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pool
  namespace: metallb
spec:
  addresses:
    - 10.0.2.200-10.0.2.210
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: advertisement
  namespace: metallb
spec:
  ipAddressPools:
    - pool

---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: metallb-controller
  namespace: metallb
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: metallb-controller
  updatePolicy:
    updateMode: "Off"
