---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb-ap
  namespace: metallb
spec:
  addresses:
    - 10.0.2.110-10.0.2.200
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: metallb-l2
  namespace: metallb
spec:
  ipAddressPools:
    - metallb-ap
