---
apiVersion: v1
kind: Namespace
metadata:
  name: reloader
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: stakater
  namespace: flux-system
spec:
  interval: 30m
  url: https://stakater.github.io/stakater-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reloader
  namespace: flux-system
spec:
  releaseName: reloader
  targetNamespace: reloader
  interval: 30m
  chart:
    spec:
      chart: reloader
      version: ">=2.0.0 <3.0.0"
      sourceRef:
        kind: HelmRepository
        name: stakater
      interval: 5m
  values:
    reloader:
      watchGlobally: true
