---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: csi-snapshotter-controller
  namespace: flux-system
spec:
  dependsOn:
    - name: csi-snapshotter-crds
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: csi-snapshotter
  path: ./deploy/kubernetes/snapshot-controller
  prune: true
  wait: true
