collections:
  - name: devsec.hardening
    version: ">=10.3.0"
    source: https://galaxy.ansible.com
  - name: hifis.toolkit
    version: ">=6.0.1"
    source: https://galaxy.ansible.com
roles:
  - name: geerlingguy.docker
    version: "7.4.7"
    source: https://galaxy.ansible.com
