---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: csi-snapshotter
  namespace: flux-system
spec:
  interval: 10m
  ref:
    semver: ">=8.0.0 <9.0.0"
  url: https://github.com/kubernetes-csi/external-snapshotter
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: csi-snapshotter-crds
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: csi-snapshotter
  path: ./client/config/crd
  prune: true
  wait: true
