---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  interval: 30m
  url: https://kubernetes-sigs.github.io/metrics-server/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  releaseName: metrics-server
  targetNamespace: kube-system
  interval: 30m
  chart:
    spec:
      chart: metrics-server
      version: ">=3.0.0 <4.0.0"
      sourceRef:
        kind: HelmRepository
        name: metrics-server
      interval: 5m
  values:
    args:
      - --kubelet-preferred-address-types=Hostname,InternalDNS,InternalIP,ExternalIP
    metrics:
      enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: kube-prometheus-stack
