apiVersion: v1
kind: Namespace
metadata:
  name: dawarich
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dawarich-db-password
  namespace: dawarich
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: scaleway-secret-manager
  target:
    name: dawarich-db-password
    template:
      data:
        username: "dawarich"
        password: "{{ .password }}"
  data:
  - secretKey: password
    remoteRef:
      key: name:homelab
      property: dawarich_db_password
      version: latest_enabled
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dawarich-secrets
  namespace: dawarich
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: scaleway-secret-manager
  target:
    name: dawarich-secrets
    template:
      data:
        secret_key_base: "{{ .secret_key_base }}"
  data:
  - secretKey: secret_key_base
    remoteRef:
      key: name:homelab
      property: dawarich_secret_key_base
      version: latest_enabled
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dawarich-oidc
  namespace: dawarich
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: scaleway-secret-manager
  target:
    name: dawarich-oidc
    template:
      type: Opaque
      data:
        oidc_client_id: "{{ .oidc_client_id }}"
        oidc_client_secret: "{{ .oidc_client_secret }}"
  data:
  - secretKey: oidc_client_id
    remoteRef:
      key: name:homelab
      property: pocket_id_oidc_client_id
      version: latest_enabled
  - secretKey: oidc_client_secret
    remoteRef:
      key: name:homelab
      property: pocket_id_oidc_client_secret
      version: latest_enabled
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: dawarich-postgres
  namespace: dawarich
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgis:17-3.5
  primaryUpdateStrategy: unsupervised
  storage:
    size: 10Gi
    storageClass: longhorn
  bootstrap:
    initdb:
      database: dawarich_production
      owner: dawarich
      secret:
        name: dawarich-db-password
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS "postgis"
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: dawarich-postgres
  namespace: dawarich
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: dawarich-postgres
  podMetricsEndpoints:
  - port: metrics
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dawarich-redis-data
  namespace: dawarich
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dawarich-public
  namespace: dawarich
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dawarich-watched
  namespace: dawarich
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dawarich-storage
  namespace: dawarich
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: dawarich
  namespace: flux-system
spec:
  image: docker.io/freikin/dawarich
  interval: 1h
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: dawarich
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: dawarich
  filterTags:
    pattern: '^(?P<version>[0-9]+\.[0-9]+\.[0-9]+)$'
    extract: '$version'
  policy:
    semver:
      range: ">=0.0.0 <1.0.0"
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: dawarich-image-updates
  namespace: flux-system
spec:
  providerRef:
    name: alertmanager
  eventSeverity: info
  eventMetadata:
    source: flux
  eventSources:
    - kind: ImagePolicy
      name: dawarich
  summary: "New Dawarich version available"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dawarich-redis
  namespace: dawarich
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: dawarich-redis
  template:
    metadata:
      labels:
        app: dawarich-redis
      annotations:
        backup.velero.io/backup-volumes-excludes: data
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: redis
        image: docker.io/valkey/valkey:8.1.5-alpine # {"$imagepolicy": "flux-system:valkey"}
        ports:
        - containerPort: 6379
          name: redis
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - valkey-cli
            - ping
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: dawarich-redis-data
---
apiVersion: v1
kind: Service
metadata:
  name: dawarich-redis
  namespace: dawarich
spec:
  selector:
    app: dawarich-redis
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dawarich-web
  namespace: dawarich
  annotations:
    secret.reloader.stakater.com/reload: "dawarich-secrets,dawarich-db-password,dawarich-oidc"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: dawarich-web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dawarich-web
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: dawarich
        image: docker.io/freikin/dawarich:0.37.3
        command: ["web-entrypoint.sh"]
        args: ["bin/rails", "server", "-p", "3000", "-b", "::"]
        ports:
        - containerPort: 3000
          name: http
        - containerPort: 9394
          name: metrics
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
        env:
        - name: RAILS_ENV
          value: "production"
        - name: REDIS_URL
          value: "redis://dawarich-redis:6379/0"
        - name: DATABASE_HOST
          value: "dawarich-postgres-rw"
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_USERNAME
          value: "dawarich"
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dawarich-db-password
              key: password
        - name: DATABASE_NAME
          value: "dawarich_production"
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: dawarich-secrets
              key: secret_key_base
        - name: APPLICATION_HOSTS
          value: "dawarich.sonley.dev,localhost"
        - name: APPLICATION_PROTOCOL
          value: "https"
        - name: TIME_ZONE
          value: "Europe/London"
        - name: DISTANCE_UNIT
          value: "km"
        - name: RAILS_MAX_THREADS
          value: "5"
        - name: SELF_HOSTED
          value: "true"
        - name: PROMETHEUS_EXPORTER_ENABLED
          value: "true"
        - name: PROMETHEUS_EXPORTER_HOST
          value: "0.0.0.0"
        - name: PROMETHEUS_EXPORTER_PORT
          value: "9394"
        - name: RAILS_LOG_TO_STDOUT
          value: "true"
        - name: STORE_GEODATA
          value: "true"
        - name: MIN_MINUTES_SPENT_IN_CITY
          value: "60"
        - name: OIDC_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: dawarich-oidc
              key: oidc_client_id
        - name: OIDC_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: dawarich-oidc
              key: oidc_client_secret
        - name: OIDC_ISSUER
          value: "https://pocket-id.sonley.dev"
        - name: OIDC_REDIRECT_URI
          value: "https://dawarich.sonley.dev/users/auth/openid_connect/callback"
        - name: OIDC_PROVIDER_NAME
          value: "Pocket ID"
        - name: OIDC_AUTO_REGISTER
          value: "true"
        startupProbe:
          tcpSocket:
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 30
        livenessProbe:
          tcpSocket:
            port: 3000
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: 3000
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: tmp
          mountPath: /var/app/tmp
        - name: public
          mountPath: /var/app/public
        - name: watched
          mountPath: /var/app/tmp/imports/watched
        - name: storage
          mountPath: /var/app/storage
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
      volumes:
      - name: tmp
        emptyDir: {}
      - name: public
        persistentVolumeClaim:
          claimName: dawarich-public
      - name: watched
        persistentVolumeClaim:
          claimName: dawarich-watched
      - name: storage
        persistentVolumeClaim:
          claimName: dawarich-storage
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dawarich-sidekiq
  namespace: dawarich
  annotations:
    secret.reloader.stakater.com/reload: "dawarich-secrets,dawarich-db-password,dawarich-oidc"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: dawarich-sidekiq
  template:
    metadata:
      labels:
        app.kubernetes.io/name: dawarich-sidekiq
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: sidekiq
        image: docker.io/freikin/dawarich:0.37.3
        command: ["sidekiq-entrypoint.sh"]
        args: ["sidekiq"]
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
        env:
        - name: RAILS_ENV
          value: "production"
        - name: REDIS_URL
          value: "redis://dawarich-redis:6379/0"
        - name: DATABASE_HOST
          value: "dawarich-postgres-rw"
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_USERNAME
          value: "dawarich"
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dawarich-db-password
              key: password
        - name: DATABASE_NAME
          value: "dawarich_production"
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: dawarich-secrets
              key: secret_key_base
        - name: APPLICATION_HOSTS
          value: "dawarich.sonley.dev,localhost"
        - name: APPLICATION_PROTOCOL
          value: "https"
        - name: TIME_ZONE
          value: "Europe/London"
        - name: DISTANCE_UNIT
          value: "km"
        - name: BACKGROUND_PROCESSING_CONCURRENCY
          value: "5"
        - name: SELF_HOSTED
          value: "true"
        - name: PROMETHEUS_EXPORTER_ENABLED
          value: "true"
        - name: PROMETHEUS_EXPORTER_HOST
          value: "dawarich"
        - name: PROMETHEUS_EXPORTER_PORT
          value: "9394"
        - name: RAILS_LOG_TO_STDOUT
          value: "true"
        - name: STORE_GEODATA
          value: "true"
        volumeMounts:
        - name: tmp
          mountPath: /var/app/tmp
        - name: public
          mountPath: /var/app/public
        - name: watched
          mountPath: /var/app/tmp/imports/watched
        - name: storage
          mountPath: /var/app/storage
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
      volumes:
      - name: tmp
        emptyDir: {}
      - name: public
        persistentVolumeClaim:
          claimName: dawarich-public
      - name: watched
        persistentVolumeClaim:
          claimName: dawarich-watched
      - name: storage
        persistentVolumeClaim:
          claimName: dawarich-storage
---
apiVersion: v1
kind: Service
metadata:
  name: dawarich
  namespace: dawarich
  labels:
    app.kubernetes.io/name: dawarich
spec:
  selector:
    app.kubernetes.io/name: dawarich-web
  ports:
  - port: 3000
    targetPort: 3000
    name: http
  - port: 9394
    targetPort: 9394
    name: metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dawarich
  namespace: monitoring
  labels:
    app: dawarich
    app.kubernetes.io/name: dawarich
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: dawarich
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
    - dawarich
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: dawarich
  namespace: dawarich
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Dawarich"
    gethomepage.dev/description: "Location History"
    gethomepage.dev/group: "Applications"
    gethomepage.dev/icon: "dawarich.png"
    gethomepage.dev/href: "https://dawarich.sonley.dev"
    gethomepage.dev/pod-selector: "app.kubernetes.io/name=dawarich-web"
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`dawarich.sonley.dev`)
      services:
        - kind: Service
          name: dawarich
          namespace: dawarich
          port: 3000
