---
apiVersion: v1
kind: Namespace
metadata:
  name: home-assistant
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: home-assistant-config
  namespace: home-assistant
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: scaleway-secret-manager
  target:
    name: home-assistant-config
  data:
  - secretKey: configuration.yaml
    remoteRef:
      key: name:home-assistant-config
      version: latest_enabled
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: home-assistant
  namespace: flux-system
spec:
  interval: 30m
  url: https://pajikos.github.io/home-assistant-helm-chart/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: flux-system
spec:
  releaseName: home-assistant
  targetNamespace: home-assistant
  interval: 30m
  chart:
    spec:
      chart: home-assistant
      version: ">=0.0.0 <1.0.0"
      sourceRef:
        kind: HelmRepository
        name: home-assistant
      interval: 5m
  values:
    podAnnotations:
      secret.reloader.stakater.com/reload: "home-assistant-config"
    ingress:
      external: true
    serviceMonitor:
      enabled: true
      labels:
        release: kube-prometheus-stack
    configuration:
      enabled: false
    persistence:
      enabled: true
      size: 15Gi
      storageClass: longhorn
      accessMode: ReadWriteOnce
    initContainers:
    - name: merge-config
      image: mikefarah/yq:4
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      command:
      - sh
      - -c
      - |
        if [ ! -f /config/configuration.yaml ]; then
          echo "No existing configuration found, copying from secret..."
          cp /tmp/config-template/configuration.yaml /config/configuration.yaml
        else
          echo "Existing configuration found, merging with secret..."
          yq eval-all '. as $item ireduce ({}; . * $item)' /config/configuration.yaml /tmp/config-template/configuration.yaml > /tmp/merged.yaml
          mv /tmp/merged.yaml /config/configuration.yaml
          echo "Configuration merged successfully"
        fi
      volumeMounts:
      - name: hass-config
        mountPath: /tmp/config-template
      - name: home-assistant
        mountPath: /config
    additionalVolumes:
    - name: hass-config
      secret:
        secretName: home-assistant-config
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`home-assistant.sonley.dev`)
    services:
    - kind: Service
      name: home-assistant
      namespace: home-assistant
      port: 8080
