---
apiVersion: v1
kind: Namespace
metadata:
  name: home-assistant
---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  namespace: home-assistant
  labels:
    app.kubernetes.io/name: home-assistant
spec:
  clusterIP: None
  ports:
    - name: http
      port: 8123
      targetPort: 8123
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: home-assistant
  namespace: home-assistant
  labels:
    kubernetes.io/service-name: home-assistant
addressType: IPv4
endpoints:
  - addresses:
      - 10.0.2.251
ports:
  - port: 8123
    protocol: TCP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`home-assistant.sonley.dev`)
      kind: Rule
      services:
        - kind: Service
          name: home-assistant
          namespace: home-assistant
          port: 8123
---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant-observer
  namespace: home-assistant
spec:
  clusterIP: None
  ports:
    - port: 4357
      targetPort: 4357
---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: home-assistant-observer
  namespace: home-assistant
  labels:
    kubernetes.io/service-name: home-assistant-observer
addressType: IPv4
endpoints:
  - addresses:
      - 10.0.2.251
ports:
  - port: 4357
    protocol: TCP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: home-assistant-observer
  namespace: home-assistant
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`ha-observer.sonley.dev`)
      kind: Rule
      services:
        - kind: Service
          name: home-assistant-observer
          namespace: home-assistant
          port: 4357
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: home-assistant-prometheus-token
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: scaleway-secret-manager
    kind: ClusterSecretStore
  target:
    name: home-assistant-prometheus-token
  data:
    - secretKey: token
      remoteRef:
        key: name:homelab
        property: home_assistant_prometheus_token
        version: latest_enabled
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: home-assistant
  namespace: monitoring
  labels:
    app.kubernetes.io/name: home-assistant
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: home-assistant
  namespaceSelector:
    matchNames:
      - home-assistant
  endpoints:
    - port: http
      path: /api/prometheus
      interval: 30s
      scrapeTimeout: 10s
      authorization:
        credentials:
          name: home-assistant-prometheus-token
          key: token
