apiVersion: v1
kind: Namespace
metadata:
  name: homebox
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homebox-data
  namespace: homebox
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homebox-oidc
  namespace: homebox
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: scaleway-secret-manager
    kind: ClusterSecretStore
  target:
    name: homebox-oidc
    template:
      type: Opaque
      data:
        oidc_client_id: "{{ .oidc_client_id }}"
        oidc_client_secret: "{{ .oidc_client_secret }}"
  data:
  - secretKey: oidc_client_id
    remoteRef:
      key: name:homelab
      property: pocket_id_oidc_client_id
      version: latest_enabled
  - secretKey: oidc_client_secret
    remoteRef:
      key: name:homelab
      property: pocket_id_oidc_client_secret
      version: latest_enabled
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: homebox
  namespace: flux-system
spec:
  image: ghcr.io/sysadminsmedia/homebox
  interval: 10m
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: homebox
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: homebox
  filterTags:
    pattern: '^(?P<version>[0-9]+\.[0-9]+\.[0-9]+)$'
    extract: '$version'
  policy:
    semver:
      range: ">=0.0.0 <1.0.0"
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: homebox
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: |
        chore(homebox): update image to {{range .Updated.Images}}{{println .}}{{end}}
    push:
      branch: main
  update:
    path: ./apps/homelab/homebox.yaml
    strategy: Setters
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homebox
  namespace: homebox
  annotations:
    secret.reloader.stakater.com/reload: "homebox-oidc"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: homebox
  template:
    metadata:
      labels:
        app.kubernetes.io/name: homebox
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: homebox
        image: ghcr.io/sysadminsmedia/homebox:0.22.3 # {"$imagepolicy": "flux-system:homebox"}
        ports:
        - containerPort: 7745
          name: http
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
        env:
        - name: HBOX_LOG_LEVEL
          value: "info"
        - name: HBOX_LOG_FORMAT
          value: "text"
        - name: HBOX_WEB_MAX_UPLOAD_SIZE
          value: "50"
        - name: HBOX_OPTIONS_ALLOW_REGISTRATION
          value: "false"
        - name: HBOX_OPTIONS_ALLOW_LOCAL_LOGIN
          value: "false"
        - name: HBOX_OPTIONS_GITHUB_RELEASE_CHECK
          value: "false"
        - name: TZ
          value: "Europe/Paris"
        - name: HBOX_OPTIONS_TRUST_PROXY
          value: "true"
        - name: HBOX_OIDC_ENABLED
          value: "true"
        - name: HBOX_OIDC_ISSUER_URL
          value: "https://pocket-id.sonley.dev"
        - name: HBOX_OIDC_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: homebox-oidc
              key: oidc_client_id
        - name: HBOX_OIDC_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: homebox-oidc
              key: oidc_client_secret
        - name: HBOX_OIDC_AUTO_REDIRECT
          value: "true"
        - name: HBOX_OIDC_BUTTON_TEXT
          value: "Sign in with Pocket ID"
        livenessProbe:
          httpGet:
            path: /api/v1/status
            port: 7745
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/v1/status
            port: 7745
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: data
          mountPath: /data
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: homebox-data
---
apiVersion: v1
kind: Service
metadata:
  name: homebox
  namespace: homebox
  labels:
    app.kubernetes.io/name: homebox
spec:
  selector:
    app.kubernetes.io/name: homebox
  ports:
  - port: 7745
    targetPort: 7745
    name: http
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homebox
  namespace: homebox
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Homebox"
    gethomepage.dev/description: "Home Inventory"
    gethomepage.dev/group: "Applications"
    gethomepage.dev/icon: "homebox.png"
    gethomepage.dev/href: "https://homebox.sonley.dev"
    gethomepage.dev/pod-selector: "app.kubernetes.io/name=homebox"
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`homebox.sonley.dev`)
      services:
        - kind: Service
          name: homebox
          namespace: homebox
          port: 7745
