apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: homepage
  namespace: flux-system
spec:
  image: ghcr.io/gethomepage/homepage
  interval: 10m
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: homepage
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: homepage
  policy:
    semver:
      range: ">=1.0.0 <2.0.0"
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: homepage
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: |
        chore(homepage): update image to {{range .Updated.Images}}{{println .}}{{end}}
    push:
      branch: main
  update:
    path: ./apps/homelab/homepage.yaml
    strategy: Setters
---
apiVersion: v1
kind: Namespace
metadata:
  name: homepage
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-api-keys
  namespace: homepage
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: scaleway-secret-manager
    kind: ClusterSecretStore
  target:
    name: homepage-api-keys
    template:
      type: Opaque
      data:
        immich-api-key: "{{ .immich_api_key }}"
        mealie-api-key: "{{ .mealie_api_key }}"
  data:
  - secretKey: immich_api_key
    remoteRef:
      key: name:homelab
      property: immich_homepage_api_key
      version: latest_enabled
  - secretKey: mealie_api_key
    remoteRef:
      key: name:homelab
      property: mealie_homepage_api_key
      version: latest_enabled
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: homepage
  namespace: homepage
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: homepage
rules:
  - apiGroups: [""]
    resources: ["namespaces", "pods", "nodes"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list"]
  - apiGroups: ["extensions", "networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list"]
  - apiGroups: ["traefik.io"]
    resources: ["ingressroutes"]
    verbs: ["get", "list"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["nodes", "pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: homepage
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: homepage
subjects:
  - kind: ServiceAccount
    name: homepage
    namespace: homepage
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage
data:
  kubernetes.yaml: |
    mode: cluster
    traefik: true
  settings.yaml: |
    title: Homelab
    theme: dark
    color: slate
    headerStyle: clean
    statusStyle: dot
    useEqualHeights: true
    layout:
      Applications:
        style: row
        columns: 2
      More Applications:
        style: row
        columns: 4
      Infrastructure:
        style: row
        columns: 4
      Monitoring:
        style: row
        columns: 4
      Widgets:
        style: row
        columns: 3
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
  services.yaml: |
    []
  bookmarks.yaml: |
    []
  docker.yaml: |
    []
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: homepage
  labels:
    app: homepage
  annotations:
    configmap.reloader.stakater.com/reload: "homepage-config"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      serviceAccountName: homepage
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      initContainers:
        - name: copy-config
          image: busybox:latest
          command:
            - sh
            - -c
            - |
              cp /config-templates/* /app/config/
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - name: config-templates
              mountPath: /config-templates
            - name: config
              mountPath: /app/config
      containers:
        - name: homepage
          image: ghcr.io/gethomepage/homepage:v1.9.0 # {"$imagepolicy": "flux-system:homepage"}
          ports:
            - containerPort: 3000
              name: http
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          env:
            - name: HOMEPAGE_ALLOWED_HOSTS
              value: "homepage.sonley.dev"
            - name: HOMEPAGE_VAR_IMMICH_API_KEY
              valueFrom:
                secretKeyRef:
                  name: homepage-api-keys
                  key: immich-api-key
                  optional: true
            - name: HOMEPAGE_VAR_MEALIE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: homepage-api-keys
                  key: mealie-api-key
                  optional: true
          volumeMounts:
            - name: config
              mountPath: /app/config
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "200m"
      volumes:
        - name: config
          emptyDir: {}
        - name: config-templates
          configMap:
            name: homepage-config
---
apiVersion: v1
kind: Service
metadata:
  name: homepage
  namespace: homepage
  labels:
    app: homepage
spec:
  selector:
    app: homepage
  ports:
    - port: 3000
      targetPort: 3000
      name: http
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homepage
  namespace: homepage
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`homepage.sonley.dev`)
      services:
        - kind: Service
          name: homepage
          namespace: homepage
          port: 3000
