---
apiVersion: v1
kind: Namespace
metadata:
  name: immich
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: immich
  namespace: flux-system
spec:
  interval: 5m0s
  url: oci://ghcr.io/immich-app/immich-charts/immich
  ref:
    tag: 0.9.3
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: flux-system
spec:
  releaseName: immich
  targetNamespace: immich
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: immich
    namespace: flux-system
  values:
    replicaCount: 1
