apiVersion: v1
kind: Namespace
metadata:
  name: linkwarden
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: linkwarden-db-password
  namespace: linkwarden
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: scaleway-secret-manager
  target:
    name: linkwarden-db-password
    template:
      data:
        username: "linkwarden"
        password: "{{ .db_password }}"
  data:
  - secretKey: db_password
    remoteRef:
      key: name:linkwarden
      property: db_password
      version: latest_enabled
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: linkwarden-secrets
  namespace: linkwarden
spec:
  refreshInterval: 15m
  secretStoreRef:
    kind: ClusterSecretStore
    name: scaleway-secret-manager
  target:
    name: linkwarden-secrets
    template:
      data:
        nextauth_secret: "{{ .nextauth_secret }}"
        database_url: "postgresql://linkwarden:{{ .db_password }}@linkwarden-postgres-rw:5432/linkwarden"
  data:
  - secretKey: nextauth_secret
    remoteRef:
      key: name:linkwarden
      property: nextauth_secret
      version: latest_enabled
  - secretKey: db_password
    remoteRef:
      key: name:linkwarden
      property: db_password
      version: latest_enabled
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: linkwarden-oidc
  namespace: linkwarden
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: scaleway-secret-manager
  target:
    name: linkwarden-oidc
    template:
      type: Opaque
      data:
        oidc_client_id: "{{ .oidc_client_id }}"
        oidc_client_secret: "{{ .oidc_client_secret }}"
  data:
  - secretKey: oidc_client_id
    remoteRef:
      key: name:pocket-id
      property: oidc_client_id
      version: latest_enabled
  - secretKey: oidc_client_secret
    remoteRef:
      key: name:pocket-id
      property: oidc_client_secret
      version: latest_enabled
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: linkwarden-postgres
  namespace: linkwarden
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  primaryUpdateStrategy: unsupervised
  storage:
    size: 5Gi
    storageClass: longhorn
  bootstrap:
    initdb:
      database: linkwarden
      owner: linkwarden
      secret:
        name: linkwarden-db-password
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linkwarden-data
  namespace: linkwarden
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: linkwarden
  namespace: flux-system
spec:
  image: ghcr.io/linkwarden/linkwarden
  interval: 10m
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: linkwarden
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: linkwarden
  filterTags:
    pattern: '^v(?P<version>[0-9]+\.[0-9]+\.[0-9]+)$'
    extract: '$version'
  policy:
    semver:
      range: ">=2.0.0 <3.0.0"
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: linkwarden
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: |
        chore(linkwarden): update image to {{range .Updated.Images}}{{println .}}{{end}}
    push:
      branch: main
  update:
    path: ./apps/homelab/linkwarden.yaml
    strategy: Setters
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkwarden
  namespace: linkwarden
  annotations:
    secret.reloader.stakater.com/reload: "linkwarden-secrets,linkwarden-db-password,linkwarden-oidc"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: linkwarden
  template:
    metadata:
      labels:
        app.kubernetes.io/name: linkwarden
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: linkwarden
        image: ghcr.io/linkwarden/linkwarden:v2.13.5 # {"$imagepolicy": "flux-system:linkwarden"}
        ports:
        - containerPort: 3000
          name: http
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        env:
        - name: NEXTAUTH_URL
          value: "https://linkwarden.sonley.dev/api/v1/auth"
        - name: NEXTAUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: linkwarden-secrets
              key: nextauth_secret
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: linkwarden-secrets
              key: database_url
        - name: NEXT_PUBLIC_KEYCLOAK_ENABLED
          value: "true"
        - name: KEYCLOAK_CUSTOM_NAME
          value: "Pocket ID"
        - name: KEYCLOAK_ISSUER
          value: "https://pocket-id.sonley.dev"
        - name: KEYCLOAK_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: linkwarden-oidc
              key: oidc_client_id
        - name: KEYCLOAK_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: linkwarden-oidc
              key: oidc_client_secret
        - name: STORAGE_FOLDER
          value: "/data/data"
        - name: NEXT_PUBLIC_CREDENTIALS_ENABLED
          value: "false"
        - name: DISABLE_REGISTRATION
          value: "true"
        - name: NEXT_PUBLIC_KEYCLOAK_AUTO_REDIRECT
          value: "true"
        startupProbe:
          httpGet:
            path: /api/v1/auth/session
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 30
        livenessProbe:
          httpGet:
            path: /api/v1/auth/session
            port: 3000
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/v1/auth/session
            port: 3000
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: data
          mountPath: /data/data
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: linkwarden-data
---
apiVersion: v1
kind: Service
metadata:
  name: linkwarden
  namespace: linkwarden
  labels:
    app.kubernetes.io/name: linkwarden
spec:
  selector:
    app.kubernetes.io/name: linkwarden
  ports:
  - port: 3000
    targetPort: 3000
    name: http
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: linkwarden
  namespace: linkwarden
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Linkwarden"
    gethomepage.dev/description: "Bookmark Manager"
    gethomepage.dev/group: "Applications"
    gethomepage.dev/icon: "linkwarden.png"
    gethomepage.dev/href: "https://linkwarden.sonley.dev"
    gethomepage.dev/pod-selector: "app.kubernetes.io/name=linkwarden"
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`linkwarden.sonley.dev`)
      services:
        - kind: Service
          name: linkwarden
          namespace: linkwarden
          port: 3000
