apiVersion: v1
kind: Namespace
metadata:
  name: mealie
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-data
  namespace: mealie
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mealie-oidc
  namespace: mealie
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: scaleway-secret-manager
    kind: ClusterSecretStore
  target:
    name: mealie-oidc
    template:
      type: Opaque
      data:
        oidc_client_id: "{{ .oidc_client_id}}"
        oidc_client_secret: "{{ .oidc_client_secret}}"
  data:
  - secretKey: oidc_client_id
    remoteRef:
      key: name:pocket-id
      property: oidc_client_id
      version: latest_enabled
  - secretKey: oidc_client_secret
    remoteRef:
      key: name:pocket-id
      property: oidc_client_secret
      version: latest_enabled
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: mealie
  namespace: flux-system
spec:
  image: ghcr.io/mealie-recipes/mealie
  interval: 10m
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: mealie
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: mealie
  policy:
    semver:
      range: ">=3.0.0 <4.0.0"
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: mealie
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: |
        chore(mealie): update image to {{range .Updated.Images}}{{println .}}{{end}}
    push:
      branch: main
  update:
    path: ./apps/homelab/mealie.yaml
    strategy: Setters
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie
  namespace: mealie
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: mealie
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mealie
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 911
        runAsGroup: 911
        fsGroup: 911
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: mealie
        image: ghcr.io/mealie-recipes/mealie:v3.9.2 # {"$imagepolicy": "flux-system:mealie"}
        ports:
        - containerPort: 9000
          name: http
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
        env:
        - name: BASE_URL
          value: "https://mealie.sonley.dev"
        - name: ALLOW_SIGNUP
          value: "false"
        - name: TZ
          value: "Europe/Paris"
        - name: MAX_WORKERS
          value: "1"
        - name: WEB_CONCURRENCY
          value: "1"
        - name: API_PORT
          value: "9000"
        - name: DB_ENGINE
          value: "sqlite"
        - name: DEFAULT_GROUP
          value: "Home"
        - name: DEFAULT_HOUSEHOLD
          value: "Family"
        - name: AUTO_BACKUP_ENABLED
          value: "true"
        - name: OIDC_AUTH_ENABLED
          value: "true"
        - name: OIDC_SIGNUP_ENABLED
          value: "true"
        - name: OIDC_CONFIGURATION_URL
          value: "https://pocket-id.sonley.dev/.well-known/openid-configuration"
        - name: OIDC_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: mealie-oidc
              key: oidc_client_id
        - name: OIDC_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: mealie-oidc
              key: oidc_client_secret
        - name: OIDC_AUTO_REDIRECT
          value: "true"
        - name: ALLOW_PASSWORD_LOGIN
          value: "false"
        - name: OIDC_ADMIN_GROUP
          value: "admins"
        - name: OIDC_PROVIDER_NAME
          value: "Pocket ID"
        - name: OIDC_REMEMBER_ME
          value: "true"
        livenessProbe:
          httpGet:
            path: /api/app/about
            port: 9000
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/app/about
            port: 9000
          initialDelaySeconds: 10
          periodSeconds: 10
        volumeMounts:
        - name: data
          mountPath: /app/data
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "500m"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: mealie-data
---
apiVersion: v1
kind: Service
metadata:
  name: mealie
  namespace: mealie
  labels:
    app.kubernetes.io/name: mealie
spec:
  selector:
    app.kubernetes.io/name: mealie
  ports:
  - port: 9000
    targetPort: 9000
    name: http
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: mealie
  namespace: mealie
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`mealie.sonley.dev`)
      services:
        - kind: Service
          name: mealie
          namespace: mealie
          port: 9000
