apiVersion: v1
kind: Namespace
metadata:
  name: ntfy
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ntfy-cache
  namespace: ntfy
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ntfy-config
  namespace: ntfy
data:
  server.yml: |
    base-url: "https://ntfy.sonley.dev"
    upstream-base-url: "https://ntfy.sh"
    cache-file: "/var/cache/ntfy/cache.db"
    attachment-cache-dir: "/var/cache/ntfy/attachments"
    behind-proxy: true
    keepalive-interval: "45s"
    template-dir: "/etc/ntfy/templates"
  alertmanager.yml: |
    title: |
      {{- if eq .status "firing" }}⚠️ Firing: {{ (index .alerts 0).labels.alertname }}
      {{- else }}✅ Resolved: {{ (index .alerts 0).labels.alertname }}{{- end }}
    message: |
      {{- range .alerts }}
      {{- if .labels.kind }}{{ .labels.kind }}: {{ .labels.name }}{{ end }}
      {{- if .labels.severity }}
      Severity: {{ .labels.severity }}{{ end }}
      {{- if .annotations.message }}
      {{ .annotations.message }}{{ end }}
      {{- if .annotations.summary }}
      {{ .annotations.summary }}{{ end }}
      {{- if .annotations.description }}
      {{ .annotations.description }}{{ end }}
      {{- if .labels.namespace }}
      Namespace: {{ .labels.namespace }}{{ end }}
      {{- end }}
    priority: |
      {{- if eq (index .alerts 0).labels.severity "critical" }}5
      {{- else if eq (index .alerts 0).labels.severity "warning" }}4
      {{- else }}3{{- end }}
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: ntfy
  namespace: flux-system
spec:
  image: binwiederhier/ntfy
  interval: 10m
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: ntfy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: ntfy
  policy:
    semver:
      range: ">=2.0.0 <3.0.0"
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: ntfy
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: |
        chore(ntfy): update image to {{range .Updated.Images}}{{println .}}{{end}}
    push:
      branch: main
  update:
    path: ./apps/homelab/ntfy.yaml
    strategy: Setters
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ntfy
  namespace: ntfy
  annotations:
    configmap.reloader.stakater.com/reload: "ntfy-config"
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: ntfy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ntfy
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: ntfy
        image: binwiederhier/ntfy:v2.17.0 # {"$imagepolicy": "flux-system:ntfy"}
        args:
        - serve
        ports:
        - containerPort: 80
          name: http
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
            - ALL
        env:
        - name: TZ
          value: "Europe/Paris"
        livenessProbe:
          httpGet:
            path: /v1/health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /v1/health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
        - name: config
          mountPath: /etc/ntfy/server.yml
          subPath: server.yml
          readOnly: true
        - name: templates
          mountPath: /etc/ntfy/templates
          readOnly: true
        - name: cache
          mountPath: /var/cache/ntfy
        resources:
          requests:
            memory: "64Mi"
            cpu: "25m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: config
        configMap:
          name: ntfy-config
          items:
          - key: server.yml
            path: server.yml
      - name: templates
        configMap:
          name: ntfy-config
          items:
          - key: alertmanager.yml
            path: alertmanager.yml
      - name: cache
        persistentVolumeClaim:
          claimName: ntfy-cache
---
apiVersion: v1
kind: Service
metadata:
  name: ntfy
  namespace: ntfy
  labels:
    app.kubernetes.io/name: ntfy
spec:
  selector:
    app.kubernetes.io/name: ntfy
  ports:
  - port: 80
    targetPort: 80
    name: http
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ntfy
  namespace: ntfy
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "ntfy"
    gethomepage.dev/description: "Push Notifications"
    gethomepage.dev/group: "Monitoring"
    gethomepage.dev/icon: "ntfy.png"
    gethomepage.dev/href: "https://ntfy.sonley.dev"
    gethomepage.dev/pod-selector: "app.kubernetes.io/name=ntfy"
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`ntfy.sonley.dev`)
      services:
        - kind: Service
          name: ntfy
          namespace: ntfy
          port: 80
